spring:

  application:
    name: ${APP_NAME:blog-api}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/blog_api}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog-master.yaml

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-ui: false

  api-docs:
    path: /v3/api-docs

  show-actuator: false

rate-limit:
  enabled: ${RATE_LIMIT_ENABLED:true}

  capacity: ${RATE_LIMIT_CAPACITY:100}
  refill-tokens: ${RATE_LIMIT_REFILL_TOKENS:100}
  refill-duration-seconds: ${RATE_LIMIT_REFILL_DURATION_SECONDS:60}

  auth-capacity: ${AUTH_RATE_LIMIT_CAPACITY:10}
  auth-refill-tokens: ${AUTH_RATE_LIMIT_REFILL_TOKENS:10}
  auth-refill-duration-seconds: ${AUTH_RATE_LIMIT_REFILL_DURATION_SECONDS:60}